<a href="https://colab.research.google.com/github/arnavashta21/ecommerce-php/blob/main/102216060_ucs531_2425.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import random

data = np.random.rand(50, 50)

np.save('data.npy', data)

In [ ]:
data = np.load('data.npy')

first_row = data[0, :]

for i in range(1, data.shape[0]):
    data[i, :] = first_row

print(data)

[[0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]
 [0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]
 [0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]
 ...
 [0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]
 [0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]
 [0.48535138 0.36934172 0.75448789 ... 0.05326632 0.89156438 0.65749604]]


In [ ]:
import numpy as np

matrix = np.random.randint(0, 10, (10, 10))  # Example matrix
unique_elements = np.unique(matrix)

grouped_matrix = {element: np.argwhere(matrix == element) for element in unique_elements}
print(grouped_matrix)

{0: array([[0, 2],
       [0, 5],
       [2, 6],
       [3, 0],
       [3, 2],
       [6, 5],
       [7, 3],
       [7, 8],
       [8, 3]]), 1: array([[0, 1],
       [1, 3],
       [2, 0],
       [2, 9],
       [3, 8],
       [4, 3],
       [4, 5],
       [5, 2],
       [5, 8],
       [7, 6],
       [7, 7]]), 2: array([[4, 1],
       [4, 9],
       [5, 6],
       [7, 0],
       [7, 4]]), 3: array([[0, 0],
       [1, 2],
       [1, 6],
       [1, 9],
       [4, 6],
       [5, 0],
       [6, 2],
       [7, 5],
       [8, 6],
       [9, 0],
       [9, 1]]), 4: array([[1, 8],
       [2, 5],
       [2, 8],
       [3, 7],
       [4, 0],
       [4, 8],
       [5, 3],
       [8, 4],
       [8, 5],
       [8, 7]]), 5: array([[1, 0],
       [1, 7],
       [2, 1],
       [2, 3],
       [2, 4],
       [2, 7],
       [6, 7],
       [8, 8],
       [9, 6]]), 6: array([[0, 8],
       [1, 4],
       [4, 2],
       [6, 3],
       [6, 6],
       [6, 8],
       [8, 0],
       [9, 8]]), 7: array([[0, 4],
 

In [ ]:
matA=np.random.rand(50,50)
matB=np.random.rand(50,50)

add=np.add(matA,matB)
sub=np.subtract(matA,matB)

print('Matrix A:')
print(matA)
print('\nMatrix B:')
print(matB)
print('\nAddition:')
print(add)
print('\nSubtraction:')

Matrix A:
[[0.76341625 0.31456153 0.35571568 ... 0.9950616  0.14903835 0.5928655 ]
 [0.37546007 0.93887325 0.94096286 ... 0.21899217 0.95737827 0.86254519]
 [0.5443988  0.24706932 0.56384422 ... 0.76212871 0.4277046  0.68120344]
 ...
 [0.09496811 0.86795241 0.90126556 ... 0.23928242 0.87937968 0.41682799]
 [0.61852631 0.33552374 0.46417946 ... 0.84075743 0.11056129 0.61201374]
 [0.61939672 0.34120287 0.48211357 ... 0.76387579 0.00276624 0.85213747]]

Matrix B:
[[0.4970256  0.96426806 0.21427076 ... 0.96536752 0.6456849  0.10387171]
 [0.21079007 0.55973938 0.77714093 ... 0.7208859  0.03063224 0.83381136]
 [0.13833241 0.27711285 0.5983001  ... 0.53543484 0.36322148 0.04883486]
 ...
 [0.65096011 0.7242936  0.83184045 ... 0.22453436 0.26768719 0.67025619]
 [0.73381214 0.42254855 0.09141101 ... 0.81964993 0.01963037 0.39802021]
 [0.4757324  0.37450966 0.47415494 ... 0.51512313 0.83707052 0.74604832]]

Addition:
[[1.26044185 1.27882959 0.56998645 ... 1.96042912 0.79472324 0.6967372 ]
 [0.586

In [ ]:
import numpy as np

def create_special_matrix(n):
    # Initialize the matrix
    matrix = np.zeros((n, n), dtype=int)

    # Fill the matrix with alternating even and odd numbers
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                matrix[i, j] = 2 * (i * n + j)  # Even number
            else:
                matrix[i, j] = 2 * (i * n + j) + 1  # Odd number

    return matrix

n = 5  # Change this to create a different size matrix
matrix = create_special_matrix(n)

# Print the resulting matrix
print("Generated Matrix:")
print(matrix)


Generated Matrix:
[[ 0  3  4  7  8]
 [11 12 15 16 19]
 [20 23 24 27 28]
 [31 32 35 36 39]
 [40 43 44 47 48]]


In [ ]:
def row_wise_addition(tuple_matrix):
    row_sums = []
    for row in tuple_matrix:
        row_sum = sum(row)
        row_sums.append(row_sum)
    return row_sums

# Example usage
tuple_matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9),
    (10, 11, 12)
)

# Perform row-wise element addition
result = row_wise_addition(tuple_matrix)

# Print the results
print("Tuple Matrix:")
for row in tuple_matrix:
    print(row)
print("\nRow-wise sums:")
print(result)


Tuple Matrix:
(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(10, 11, 12)

Row-wise sums:
[6, 15, 24, 33]
